<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Library</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <RootNamespace>Guinevere</RootNamespace>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>

        <!-- NuGet Package Properties -->
        <Title>Guinevere - Vulkan - SilkNET</Title>
        <PackageId>MASS4.Guinevere.Vulkan.SilkNET</PackageId>
        <Description>Vulkan via SilkNET integration for Guinevere</Description>
        <Company>MASS4</Company>
        <Product>Guinevere</Product>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
        <IncludeSymbols>true</IncludeSymbols>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <Version>1.8.0</Version>
    </PropertyGroup>

    <ItemGroup>
        <None Include="README.md" Pack="true" PackagePath="\"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Silk.NET.Input" Version="2.23.0" />
        <PackageReference Include="Silk.NET.Input.Extensions" Version="2.23.0" />
        <PackageReference Include="Silk.NET.Vulkan.Extensions.EXT" Version="2.23.0" />
        <PackageReference Include="Silk.NET.Vulkan" Version="2.23.0" />
        <PackageReference Include="Silk.NET.Vulkan.Extensions.KHR" Version="2.23.0" />
        <PackageReference Include="Silk.NET.Windowing.Common" Version="2.23.0" />
        <PackageReference Include="Silk.NET.Windowing.Glfw" Version="2.23.0" />
        <PackageReference Include="SkiaSharp" Version="4.152.1" />
        <PackageReference Include="SkiaSharp.NativeAssets.Linux" Version="4.152.1" />
        <PackageReference Include="SkiaSharp.Views.Desktop.Common" Version="4.152.1" />
        <PackageReference Include="Serilog" Version="4.4.0" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="../../Guinevere/Guinevere.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Include="../Resources/Fonts/font.ttf" />
        <EmbeddedResource Include="../Resources/Fonts/icons.ttf" />
        <EmbeddedResource Include="../Resources/Shaders/Vulkan/*.spv"/>
    </ItemGroup>
</Project>
