<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Version>5.4.0</Version>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../Guinevere/Guinevere.csproj" />
    <ProjectReference Include="../../Guinevere.Scripting/Guinevere.Scripting.csproj" />
    <ProjectReference Include="../../Guinevere.Styling/Guinevere.Styling.csproj" />
  </ItemGroup>
</Project>
